name: Database Build

on:
  schedule:
    - cron: "0 0 * * *" # Daily
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_PAT }}
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: install
        run: |
          yarn
      - name: Generate db
        id: dbgen
        env:
          G_API_KEY: ${{ secrets.G_API_KEY }}
        run: |
          yarn gen
          yarn validate
          git add db/
          git diff-index HEAD || true
          git diff-index --quiet HEAD && echo ::set-output name=DIRTY::0 || echo ::set-output name=DIRTY::1
      - name: Commit Database update
        if: steps.dbgen.outputs.DIRTY == '1'
        run: |
          echo "Need to update the DB"
          git config --global user.name 'Database Bot'
          git add db/
          git status
          git commit -am "Database Synchronization"
          git push
