name: Database Build

on:
  schedule:
    - cron: '0 0 * * *' # Daily
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_PAT }}
      - uses: actions/checkout@v2
        with:
          path: wikirepo
          repository: zekth/too-much-artisans-db.wiki
          token: ${{ secrets.BOT_PAT }}
      - id: nodeversion
        run: echo ::set-output name=NODE::$(cat .nvmrc)
      - name: restore Cache
        uses: actions/cache@master
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Use Node.js ${{steps.nodeversion.outputs.NODE}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.nodeversion.outputs.NODE }}
      - name: install
        run: |
          yarn
      - name: Generate db
        id: dbgen
        env:
          G_API_KEY: ${{ secrets.G_API_KEY }}
        run: |
          yarn gen
          yarn validate
          git add db/
          git add README.md
          git diff-index HEAD || true
          git diff-index --quiet HEAD && echo ::set-output name=DIRTY::0 || echo ::set-output name=DIRTY::1
      - name: Commit Database update
        if: steps.dbgen.outputs.DIRTY == '1'
        env:
          DISCORD_HOOK: ${{ secrets.DISCORD_HOOK }}
        run: |
          echo "Need to update the DB"
          git config --global user.name 'Database Bot'
          node scripts/discord-update.js
          git add db/
          git status
          git commit -am "Database Synchronization"
          git push
      - name: Update wiki
        run: |
          yarn gen:wiki
          rm -rf wikirepo/*
          cp -r wiki-dist/* wikirepo/
          cd wikirepo
          git config --global user.name 'Database Bot'
          git add .
          git commit -m "update-wiki"
          git push -f
